/* 7TRIBES LIFE ACADEMY — Lesson 7 keeps community planning private; public tools never create community data. */
import { academySupabase, academySession } from './academy-supabase.js';
const slug='how-communities-build', sections=['communities-systems','complaints-problems','authority','capability-before-capital','capability-map','gap-detection','businesses-infrastructure','ownership-result','sustainability','project-economics','coordination','ecosystem','build-plan','contribution','knowledge-check'];
const state={session:null,lesson:null,viewed:new Set(),completed:false};
const esc=v=>String(v||'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c])); const status=(n,t,tone='')=>{if(n){n.textContent=t;n.dataset.tone=tone;}};
function gate(node,anchor){const r=`${location.pathname}${anchor||''}`;node.dataset.tone='error';node.innerHTML=`Save your progress <a href="/account/signup.html?returnTo=${encodeURIComponent(r)}">Create a free 7Tribes account</a> to continue your Life Academy journey and return where you left off. <a href="/account/login.html?returnTo=${encodeURIComponent(r)}">Log In</a>`;}
async function section(key){if(!state.session||!state.lesson||state.viewed.has(key))return;state.viewed.add(key);await academySupabase.rpc('track_academy_lesson_section',{p_lesson_id:state.lesson.id,p_section:key});}
function observe(){if(!IntersectionObserver)return;const o=new IntersectionObserver(es=>es.filter(e=>e.isIntersecting&&e.intersectionRatio>.35).forEach(e=>section(e.target.dataset.l7Section)),{threshold:[.35]});document.querySelectorAll('[data-l7-section]').forEach(n=>o.observe(n));}
function planner(){const root=document.querySelector('[data-l7-planner]');if(!root)return;const render=()=>{const n=k=>Math.max(0,Number(root.querySelector(`[data-l7-plan="${k}"]`).value)||0),surplus=n('revenue')-n('expenses')-n('reserve'),annual=(n('expenses')+n('reserve'))*12;root.querySelector('[data-l7-plan-output]').innerHTML=`<strong>Educational scenario only</strong><p>Monthly surplus / shortfall: ${surplus.toLocaleString()} · Annual operating requirement: ${annual.toLocaleString()} · Workers: ${n('workers')}.</p><p>${surplus>=0?'Illustrative indicator: planned monthly revenue/funding covers the entered operating and reserve values.':'Illustrative indicator: entered monthly revenue/funding does not cover the entered operating and reserve values.'} This is not a feasibility determination.</p>`;section('project-economics');};root.querySelectorAll('input').forEach(i=>i.addEventListener('input',render));render();}
function problem(){const root=document.querySelector('[data-l7-problem]');if(!root)return;root.addEventListener('change',async()=>{const c=root.querySelectorAll('input:checked').length;status(root.querySelector('[data-l7-problem-status]'),c?'Good investigation starts by identifying the conditions, authorities, capabilities, and dependencies involved.':'Select conditions to turn dissatisfaction into an investigateable problem.');await section('complaints-problems');});}
function privatePlan(){const f=document.querySelector('[data-l7-plan-form]');if(!f)return;f.addEventListener('submit',async e=>{e.preventDefault();const s=f.querySelector('[data-l7-plan-status]');if(!state.session)return gate(s,'#build-plan');const d=Object.fromEntries(new FormData(f).entries());if(!d.need||!d.problem||!d.existing_capabilities||!d.gaps||!d.sustainability||!d.contribution)return status(s,'Complete the need, problem, existing capabilities, gaps, sustainability, and contribution fields before saving.','error');const {error}=await academySupabase.from('academy_lesson_exercise_responses').upsert({user_id:state.session.user.id,lesson_id:state.lesson.id,exercise_key:'community-build-plan',response:d},{onConflict:'user_id,lesson_id,exercise_key'});if(!error)await section('build-plan');status(s,error?error.message:'Your Community Build Plan and contribution were saved privately.',error?'error':'success');});}
async function quiz(){const f=document.querySelector('[data-l7-quiz-form]'),h=document.querySelector('[data-l7-quiz-questions]');if(!f||!state.lesson)return;const {data,error}=await academySupabase.rpc('get_academy_lesson_quiz',{p_lesson_id:state.lesson.id});if(error||!Array.isArray(data))return;h.innerHTML=data.map((q,i)=>`<fieldset><legend>${i+1}. ${esc(q.prompt)}</legend>${q.choices.map(c=>`<label><input type="radio" name="${esc(q.id)}" value="${esc(c.id)}"> ${esc(c.label)}</label>`).join('')}<p class="academy-feedback" data-l7-feedback="${esc(q.id)}"></p></fieldset>`).join('');f.addEventListener('submit',async e=>{e.preventDefault();const s=f.querySelector('[data-l7-quiz-status]');if(!state.session)return gate(s,'#knowledge-check');const answers=Object.fromEntries(new FormData(f).entries());if(Object.keys(answers).length<data.length)return status(s,`Answer all ${data.length} questions before submitting.`,'error');const {data:r,error:x}=await academySupabase.rpc('submit_academy_quiz',{p_lesson_id:state.lesson.id,p_answers:answers});if(x)return status(s,x.message,'error');r.feedback.forEach(i=>status(f.querySelector(`[data-l7-feedback="${CSS.escape(i.id)}"]`),i.explanation,i.correct?'success':''));await section('knowledge-check');status(s,r.passed?`Passed: ${r.score}/${data.length}. Save your private plan, then record completion.`:`Score: ${r.score}/${data.length}. Review the explanations and try again.`,r.passed?'success':'error');});}
async function moduleComplete(){const b=document.querySelector('[data-l7-module]');const {data,error}=await academySupabase.rpc('complete_academy_module_one',{p_module_id:state.lesson.module_id});if(error){status(document.querySelector('[data-l7-completion-status]'),'Lesson 7 is complete. Module completion will record after all seven lessons are complete.','');return;}const {data:sum}=await academySupabase.rpc('get_academy_module_one_summary');b.classList.remove('academy-hidden');b.querySelector('[data-l7-module-copy]').textContent='You have completed the foundation of 7Tribes Life Academy. Learn → Map → Connect → Organize → Build → Circulate → Measure → Transfer.';b.querySelector('[data-l7-module-summary]').textContent=`Lessons completed: ${sum.lessons_completed}/7 · Knowledge checks passed: ${sum.knowledge_checks_passed} · Capability exercises completed: ${sum.capability_exercises_completed} · Community Build Plan completed: ${sum.community_build_plan_completed?'Yes':'No'}`;}
function done(){document.querySelector('[data-l7-complete]').classList.add('academy-hidden');document.querySelector('[data-l7-completion-heading]').textContent='Lesson 7 completed';document.querySelector('[data-l7-completion-copy]').textContent='You have completed the final lesson in Module 1.';status(document.querySelector('[data-l7-completion-status]'),'LESSON 7 COMPLETED ✓','success');moduleComplete();}
function completion(){const b=document.querySelector('[data-l7-complete]');b.addEventListener('click',async()=>{const s=document.querySelector('[data-l7-completion-status]');if(!state.session)return gate(s,'#complete');b.disabled=true;const {error}=await academySupabase.rpc('complete_academy_lesson7',{p_lesson_id:state.lesson.id});if(error)status(s,error.message,'error');else{state.completed=true;done();}b.disabled=false;});}
document.addEventListener('DOMContentLoaded',async()=>{try{state.session=await academySession();document.documentElement.dataset.academyAuth=state.session?'signed-in':'signed-out';const {data,error}=await academySupabase.from('academy_lessons').select('id,module_id').eq('slug',slug).maybeSingle();if(error)throw error;state.lesson=data;if(state.session){const {data:c}=await academySupabase.from('academy_completions').select('completed_at').eq('lesson_id',data.id).maybeSingle();state.completed=Boolean(c?.completed_at);if(state.completed)done();}observe();problem();planner();privatePlan();await quiz();completion();}catch(_){}});
